# Numpy

In [1]:
import numpy as np

<br/>
<br/>
<br/>
<br/>

#### Q1) 아래 리스트를 이용하여 1차원 배열을 생성하세요.
  - [103, 815, 571, 934, 599, 945,  71, 669, 639, 116, 423, 985, 814, 506, 792, 295, 914, 397, 654,  32, 859, 321, 850, 340, 325]

In [2]:
# code here
arr1 = 
arr1

array([103, 815, 571, 934, 599, 945,  71, 669, 639, 116, 423, 985, 814,
       506, 792, 295, 914, 397, 654,  32, 859, 321, 850, 340, 325])

<br/>
<br/>

#### Q2) arr1의 shape을 5행 5열로 변경하여 arr2에 저장하세요.
 - reshape

In [3]:
# code here
arr2 = 
arr2

array([[103, 815, 571, 934, 599],
       [945,  71, 669, 639, 116],
       [423, 985, 814, 506, 792],
       [295, 914, 397, 654,  32],
       [859, 321, 850, 340, 325]])

<br/>
<br/>

#### Q3) arr2의 요소 중 71에 10을 곱하세요.
 - 인덱싱/불리언 인덱싱 및 수정

In [4]:
# code here

arr2

array([[103, 815, 571, 934, 599],
       [945, 710, 669, 639, 116],
       [423, 985, 814, 506, 792],
       [295, 914, 397, 654,  32],
       [859, 321, 850, 340, 325]])

<br/>
<br/>

#### Q4) arr2의 요소 중 가운데 위치한 9개 요소 (3개 행과 3개 열)을 출력하세요.
 - 슬라이싱

In [5]:
# code here


array([[710, 669, 639],
       [985, 814, 506],
       [914, 397, 654]])

<br/>
<br/>

#### Q5) arr2의 요소 중 가운데 위치한 9개 요소에 10을 곱하세요.
 - 슬라이싱 및 수정

In [6]:
# code here

arr2

array([[ 103,  815,  571,  934,  599],
       [ 945, 7100, 6690, 6390,  116],
       [ 423, 9850, 8140, 5060,  792],
       [ 295, 9140, 3970, 6540,   32],
       [ 859,  321,  850,  340,  325]])

<br/>
<br/>

#### Q6) arr2의 요소 중 1000 이상인 요소만 추출하여 형태를 3행 3열로 변경한 후 출력하세요.
 - 불리언 인덱싱, reshape

In [7]:
# code here


array([[7100, 6690, 6390],
       [9850, 8140, 5060],
       [9140, 3970, 6540]])

<br/>
<br/>

#### Q7) arr2의 중앙에 있는 값을 -1로 변경한 후 출력하세요.

In [8]:
# code here

arr2

array([[ 103,  815,  571,  934,  599],
       [ 945, 7100, 6690, 6390,  116],
       [ 423, 9850,   -1, 5060,  792],
       [ 295, 9140, 3970, 6540,   32],
       [ 859,  321,  850,  340,  325]])

<br/>
<br/>

#### Q8) arr2의 열 별(행과 행) 평균과 표준편차를 출력하세요.

In [9]:
# code here


array([ 525. , 5445.2, 2416. , 3852.8,  372.8])

array([ 325.37486074, 4086.27827736, 2544.80891228, 2682.34661444,
        286.79986053])

<br/>
<br/>

#### Q9) arr2의 행 별(열과 열) 평균과 표준편차를 출력하세요.

In [11]:
# code here


array([ 604.4, 4248.2, 3224.8, 3995.4,  539. ])

array([ 284.79297744, 3055.11586687, 3779.83118142, 3531.12002628,
        257.69827318])

<br/>
<br/>

#### Q10)  arr2의 요소 중 1000 미만인 요소는 -1으로, 1000 이상인 요소는 arr2의 값을 유지하여 arr3에 저장하세요.

In [13]:
# code here
arr3 = 
arr3

array([[  -1,   -1,   -1,   -1,   -1],
       [  -1, 7100, 6690, 6390,   -1],
       [  -1, 9850,   -1, 5060,   -1],
       [  -1, 9140, 3970, 6540,   -1],
       [  -1,   -1,   -1,   -1,   -1]])

<br/>
<br/>

#### Q11) arr3의 열 별(행과 행) 평균을 출력하세요

In [15]:
# code here


array([-1.0000e+00,  5.2176e+03,  2.1314e+03,  3.5976e+03, -1.0000e+00])

<br/>
<br/>

#### Q12) arr3의 전체 평균을 출력하세요.

In [16]:
# code here


2188.92

<br/>
<br/>

#### Q13) arr3의 요소 중 음수인 요소는 0으로, 나머지 요소는 arr3의 값을 유지하여 arr4에 저장하세요.

In [17]:
# code here
arr4 = 
arr4

array([[   0,    0,    0,    0,    0],
       [   0, 7100, 6690, 6390,    0],
       [   0, 9850,    0, 5060,    0],
       [   0, 9140, 3970, 6540,    0],
       [   0,    0,    0,    0,    0]])